name: publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

permissions: {}

env:
  IMAGE: ghcr.io/crazyscot/container-autobuild-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TAG: |-
        ${{ case(
          github.event_name == 'push', github.ref_name,
          'unknown'
        ) }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build . --tag ${{ env.IMAGE }}:${{ env.TAG }}
      - name: Push the image
        if: ${{ github.event_name == 'push' }}
        run: docker push ${{ env.IMAGE }}:${{ env.TAG }}
